# Generated by Django 4.2.13 on 2024-06-04 13:31

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("curd_sql_demo", "0001_initial"),
    ]

    operations = [
        migrations.DeleteModel(
            name="Document",
        ),
    ]
